fix: better handling of mapping file

diff --git a/genesis-infra-api/action.yml b/genesis-infra-api/action.yml
--- a/genesis-infra-api/action.yml
+++ b/genesis-infra-api/action.yml
@@ -150,13 +150,6 @@ inputs:
     description: Name of the VPC Service Controls perimeter to add the new project to.
     required: true
 
-  mapping_type:
-    description: >
-      Name of the JSON file that maps Terraform output variables to GitHub variables and secrets.
-      This file must be located in the action's root directory. Defaults to "tf_outputs_mapping.json".
-    required: false
-    default: "base_infra_mappings"
-
 runs:
   using: composite
   steps:
@@ -251,13 +244,17 @@ runs:
         GH_TOKEN: ${{ inputs.repo_admin_token }}
         ENVIRONMENT: ${{ inputs.environment }}
         REPO: ${{ inputs.github_repo_name }}
-        MAPPING_FILE: ${{ github.action_path }}/${{ inputs.mapping_type }}.json
       run: |
-        if [[ ! -f "$MAPPING_FILE" ]]; then
-          echo "Error: mapping file not found: $MAPPING_FILE" >&2
+        if ${{ inputs.action }} == 'create-basic-infra'; then
+          export MAPPING_FILE=${{ github.action_path }}/base_infra_mappings.json
+        elif ${{ inputs.action }} == 'create-data-product'; then
+          export MAPPING_FILE=${{ github.action_path }}/data_product_creation_mappings.json
+        else
+          echo "Error: no mapping file for action: ${{ inputs.action }}" >&2
           exit 1
         fi
-
+        echo "Using mapping file: $MAPPING_FILE"
+        
         if [[ -z "$REPO" ]]; then
           REPO=$(terraform output -raw github_repo_name)
         fi
